### ISSUE TITLE
Chints, plis put README

### ISSUE THREAD

**Issue by Gituser143** [siddhantrao23/sadenstein#1]
Greetings,
I recently stumbled upon this repository and was quite intrigued by it. I made a rather fair attempt to perceive the intended use of the said repository but my failure was quite exorbitant. "Why?" you ask? Because you couldn't make a README to describe what the intended characteristics are you blithering idiot. I request you to kindly acknowledge the same.

Thank you

**Comment by siddhantrao23** [comment]
Greetings,
I shall do the needful by tomorrow. Thank you for your advice.
OK BYE BHARGEEEE
